In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
def printing_matrix(string1, string2, lenstr1, lenstr2, F):
    print('  ', end = "")        
    for j in range(lenstr2):
        print("\033[32m {}".format(string2[j]), end = "")
    for i in range(lenstr1):
        print('')
        print("\033[32m {}".format(string1[i]), end="") 
        for j in range(lenstr2):
            if string1[i] == string2[j]:
                print("\033[31m {}".format(F[i+1][j+1]), end = "")
            else:
                print("\033[34m {}".format(F[i+1][j+1]), end = "")
               

    print('  ')

## Hamming distance

In [3]:
def hamming_distance(string1, string2):
    distance = 0
    L = len(string1)
    for i in range(L):
        if string1[i] != string2[i]:
            distance += 1
    print('Расстояние Хемминга:',distance)
        
    return distance

In [4]:
hamming_distance('12354', '12453')

Расстояние Хемминга: 2


2

## Longest common subsequence problem

In [5]:
# Longest common subsequence problem
def LCS(string1, string2):
    n = len(string1)
    m = len(string2)
    F = [[0] * (m + 1) for i in range(n + 1)]
    for i in range(1, n + 1):
        for j in range(1, m + 1):
            if string1[i - 1] == string2[j - 1]:
                F[i][j] = F[i - 1][j - 1] + 1 
            else: 
                F[i][j] = max(F[i - 1][j], F[i][j - 1]) 
    print(F[n][m])
    print(np.matrix(F))

    Ans = []
    i = n
    j = m
    while i > 0 and j > 0:
        if string1[i - 1] == string2[j - 1]:
            Ans.append(string1[i - 1])
            i -= 1
            j -= 1
        elif F[i - 1][j] == F[i][j]:
            i -= 1 
        else: 
            j -= 1
     
    Ans = Ans[::-1]
    return(Ans)

In [6]:
LCS('asdf','a23f')

2
[[0 0 0 0 0]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 2]]


['a', 'f']

## Levenshtain distance

In [7]:
# Levenshtain
def Levenshtain(string1, string2):
    # String1 and string2 are sequences.
    lenstr1 = len(string1)
    lenstr2 = len(string2)
    F = [[0] * (lenstr2 + 1) for i in range(lenstr1 + 1)]
    
    # Filling in a zero column and row.
    for i in range(1,lenstr1+1):
        F[i][0] = i
    for j in range(1,lenstr2+1):
        F[0][j] = j
        
    # Filling in the matrix
    for i in range(lenstr1):
        for j in range(lenstr2):
            if string1[i] == string2[j]:
                cost = 0
            else:
                cost = 1
            F[i+1][j+1] = min(F[i][j+1] + 1,  # deletion
                              F[i+1][j] + 1,  # insert
                              F[i][j] + cost)  # change
                
    # Print the matrix with red colour for matching elements, green colour for sequenses, blue colour for others.    
    printing_matrix(string1, string2, lenstr1, lenstr2, F)
    return(F[lenstr1][lenstr2])


In [8]:
Levenshtain('adsf','da1f')

   d a 1 f
 a 1 1 2 3
 d 1 2 2 3
 s 2 2 3 3
 f 3 3 3 3  


3

## Damerau-Levenshtain distance

In [9]:
# Damerau-Levenshtain
def DL(string1, string2):
    # String1 and string2 are sequences.
    lenstr1 = len(string1)
    lenstr2 = len(string2)
    F = [[0] * (lenstr2 + 1) for i in range(lenstr1 + 1)]
    
    # Filling in a zero column and row.
    for i in range(1,lenstr1+1):
        F[i][0] = i
    for j in range(1,lenstr2+1):
        F[0][j] = j
        
    # Filling in the matrix
    for i in range(lenstr1):
        for j in range(lenstr2):
            if string1[i] == string2[j]:
                cost = 0
            else:
                cost = 1
            F[i+1][j+1] = min(F[i][j+1] + 1,  # deletion
                              F[i+1][j] + 1,  # insert
                              F[i][j] + cost)  # change
            
            # After count of minimum with deletion, insert and change try to find transposition.             
            if i > 0 and j > 0 and string1[i] == string2[j-1] and string1[i-1] == string2[j]:
                F[i+1][j+1] = min (F[i+1][j+1], F[i-1][j-1] + cost)  # minimum of deletion, insert, change and transposition
              
                
    # Print the matrix with red colour for matching elements, green colour for sequenses, blue colour for others.    
    printing_matrix(string1, string2, lenstr1, lenstr2, F)
    return(F[lenstr1][lenstr2])


In [10]:
DL('adsf','da1f')

   d a 1 f
 a 1 1 2 3
 d 1 1 2 3
 s 2 2 2 3
 f 3 3 3 2  


2

## Damerau-Levenshtain with symmetric parametrizion

In [11]:
def DL_parameter_symmetric(string1: str,
                           string2: str,
                           a: int = 10):
    # String1 and string2 are sequences, parameter a means counts of maximum elements between. 
    lenstr1 = len(string1)
    lenstr2 = len(string2)
    F = [[0] * (lenstr2 + 1) for i in range(lenstr1 + 1)]
    
    # Filling in a zero column and row.
    for i in range(1,lenstr1+1):
        F[i][0] = i
    for j in range(1,lenstr2+1):
        F[0][j] = j
        
    # Filling in the matrix
    for i in range(lenstr1):
        for j in range(lenstr2):
            if string1[i] == string2[j]:
                cost = 0
            else:
                cost=1
            F[i+1][j+1] = min(F[i][j+1] + 1,  # deletion
                              F[i+1][j] + 1,  # insert
                              F[i][j] + cost)  # change
            
            # After count of minimum with deletion, insert and change try to find transpositions: 
            # try to find i-element in string1 in string2 and j-element in string2 in string1 with maximum a-steps. 
            # If find parameter a call recursive this function for elements between transposion elements.                  
            for a in range(1, a+1):
                if i > a-1 and j > a-1 and string1[i] == string2[j-a] and string1[i-a] == string2[j]:
                    distance = DL_parameter_symmetric(string1[i-a+1:i], string2[j-a+1:j], a)  # call recursive
                    F[i+1][j+1] = min (F[i+1][j+1], F[i-a][j-a] + 1 + distance)  # minimum of deletion, insert, change and transposition
                     
    # Print the matrix with red colour for matching elements, green colour for sequenses, blue colour for others.           
    #print(np.matrix(F))    
    printing_matrix(string1, string2, lenstr1, lenstr2, F)
    return(F[lenstr1][lenstr2])

In [12]:
DL_parameter_symmetric('asdf','dssaf')
DL_parameter_symmetric('asdf','dsaf')

    
    
   d s s a f
 a 1 2 3 3 4
 s 2 1 2 3 4
 d 2 2 2 3 4
 f 3 3 3 3 3  
    
    
   s
 s 0  
   d s a f
 a 1 2 2 3
 s 2 1 2 3
 d 2 2 1 2
 f 3 3 2 1  


1

## Damerau-Levenshtein with asymmetric parametrizion

In [13]:
from typing import Optional

def DL_parameter(string1: str,
                 string2: str,
                 a: int = 10,
                 b: Optional[int] = None):    
    if b is None:
        b = a
    # String1 and string2 are sequences, parameters a and b mean counts of maximum elements between. 
   
    lenstr1 = len(string1)
    lenstr2 = len(string2)
    F = [[0] * (lenstr2 + 1) for i in range(lenstr1 + 1)]
    
    # Filling in a zero column and row.
    for i in range(1,lenstr1+1):
        F[i][0] = i
    for j in range(1,lenstr2+1):
        F[0][j] = j
        
    # Filling in the matrix
    for i in range(lenstr1):
        for j in range(lenstr2):
            if string1[i] == string2[j]:
                cost = 0
            else:
                cost=1
            F[i+1][j+1] = min(F[i][j+1] + 1,  # deletion
                              F[i+1][j] + 1,  # insert
                              F[i][j] + cost)  # change
                             
            # After count of minimum with deletion, insert and change try to find transpositions: 
            # first try to find i-element in string1 in string2 with maximum a-steps,
            # second try to find j-element in string2 in string1 with maximum b-steps. 
            # If find parameters a and b call recursive this function for elements between transposion elements.
            
            for a in range(1,a+1):
                if j > a-1 and string1[i] == string2[j-a]:  
                    for b in range(1,b+1):
                        if i > b-1 and string2[j] == string1[i-b]:
                            distance = DL_parameter(string1[i-b+1:i], string2[j-a+1:j], a, b)  # call recursive
                            F[i+1][j+1] = min (F[i+1][j+1], F[i-b][j-a] + 1 + distance)  # minimum of deletion, insert, change and transposition
                            
    # Print the matrix with red colour for matching elements, green colour for sequenses, blue colour for others.  
    printing_matrix(string1, string2, lenstr1, lenstr2, F)  
    return(F[lenstr1][lenstr2])

In [14]:
DL_parameter('asdf','dssaf')
DL_parameter('asdf','dsaf')

    
   s  
    
   s  
   s s
 s 0 1  
   d s s a f
 a 1 2 3 3 4
 s 2 1 2 3 4
 d 2 2 2 2 3
 f 3 3 3 3 2  
    
    
   s
 s 0  
   d s a f
 a 1 2 2 3
 s 2 1 2 3
 d 2 2 1 2
 f 3 3 2 1  


1

In [16]:
%%time
    
DL_parameter('x1872','x27081')
DL_parameter_symmetric('x1872','x27081')
DL('x1872','x27081')
Levenshtain('x1872','x27081')



    
   0  
   0 8
 8 1 1  
    
   7 0
 7 0 1  
   0  
   7 0 8
 8 1 2 2
 7 1 2 2  
   x 2 7 0 8 1
 x 0 1 2 3 4 5
 1 1 1 2 3 4 4
 8 2 2 2 3 3 4
 7 3 3 2 3 3 3
 2 4 3 3 3 3 3  
    
    
   x 2 7 0 8 1
 x 0 1 2 3 4 5
 1 1 1 2 3 4 4
 8 2 2 2 3 3 4
 7 3 3 2 3 4 4
 2 4 3 3 3 4 5  
   x 2 7 0 8 1
 x 0 1 2 3 4 5
 1 1 1 2 3 4 4
 8 2 2 2 3 3 4
 7 3 3 2 3 4 4
 2 4 3 3 3 4 5  
   x 2 7 0 8 1
 x 0 1 2 3 4 5
 1 1 1 2 3 4 4
 8 2 2 2 3 3 4
 7 3 3 2 3 4 4
 2 4 3 3 3 4 5  
Wall time: 29.6 ms


5

In [17]:
DL_parameter('x123456','x654321')
DL_parameter_symmetric('x123456','x654321')
DL('x123456','x654321')
Levenshtain('x123456','x654321')

    
    
   2
 2 0  
    
   3
 3 0  
    
   3 2
 2 1 1
 3 1 1  
    
   4
 4 0  
    
   4 3
 3 1 1
 4 1 1  
    
    
   3
 3 0  
   4 3 2
 2 1 2 2
 3 2 1 2
 4 2 2 1  
    
   5
 5 0  
    
   5 4
 4 1 1
 5 1 1  
    
    
   4
 4 0  
   5 4 3
 3 1 2 2
 4 2 1 2
 5 2 2 1  
    
    
   3
 3 0  
    
   4
 4 0  
    
   4 3
 3 1 1
 4 1 1  
   5 4 3 2
 2 1 2 3 3
 3 2 2 2 3
 4 3 2 2 2
 5 3 3 2 2  
   x 6 5 4 3 2 1
 x 0 1 2 3 4 5 6
 1 1 1 2 3 4 5 5
 2 2 2 2 3 4 4 5
 3 3 3 3 3 3 4 4
 4 4 4 4 3 3 3 4
 5 5 5 4 4 3 3 3
 6 6 5 5 4 4 3 3  
    
    
   2
 2 0  
    
   3
 3 0  
    
   3 2
 2 1 1
 3 1 1  
    
   4
 4 0  
    
   4 3
 3 1 1
 4 1 1  
    
    
   3
 3 0  
   4 3 2
 2 1 2 2
 3 2 1 2
 4 2 2 1  
    
   5
 5 0  
    
   5 4
 4 1 1
 5 1 1  
    
    
   4
 4 0  
   5 4 3
 3 1 2 2
 4 2 1 2
 5 2 2 1  
    
    
   3
 3 0  
    
   4
 4 0  
    
   4 3
 3 1 1
 4 1 1  
   5 4 3 2
 2 1 2 3 3
 3 2 2 2 3
 4 3 2 2 2
 5 3 3 2 2  
   x 6 5 4 3 2 1
 x 0 1 2 3 4 5 6
 1 1 1 2 3 4 5 5
 2 2 2 2 

6

In [18]:
DL_parameter('x12356','x654321')
DL_parameter_symmetric('x12356','x654321')
DL('x12356','x654321')
Levenshtain('x12356','x654321')

    
    
   2
 2 0  
   4  
   4 3
 3 1 1  
    
   4 3 2
 2 1 2 2
 3 2 1 2  
    
   5 4
 5 0 1  
   4  
   5 4 3
 3 1 2 2
 5 1 2 2  
    
   4  
   4 3
 3 1 1  
   5 4 3 2
 2 1 2 3 3
 3 2 2 2 3
 5 2 3 3 2  
   x 6 5 4 3 2 1
 x 0 1 2 3 4 5 6
 1 1 1 2 3 4 5 5
 2 2 2 2 3 4 4 5
 3 3 3 3 3 3 4 4
 5 4 4 3 4 4 3 4
 6 5 4 4 4 4 4 3  
    
    
   2
 2 0  
    
   x 6 5 4 3 2 1
 x 0 1 2 3 4 5 6
 1 1 1 2 3 4 5 5
 2 2 2 2 3 4 4 5
 3 3 3 3 3 3 4 4
 5 4 4 3 4 4 4 5
 6 5 4 4 4 5 5 5  
   x 6 5 4 3 2 1
 x 0 1 2 3 4 5 6
 1 1 1 2 3 4 5 5
 2 2 2 2 3 4 4 5
 3 3 3 3 3 3 4 5
 5 4 4 3 4 4 4 5
 6 5 4 4 4 5 5 5  
   x 6 5 4 3 2 1
 x 0 1 2 3 4 5 6
 1 1 1 2 3 4 5 5
 2 2 2 2 3 4 4 5
 3 3 3 3 3 3 4 5
 5 4 4 3 4 4 4 5
 6 5 4 4 4 5 5 5  


5