In [23]:
import numpy as fp
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from typing import Optional

def LCS_ch(
            string1: str,
            string2: str,
                 a: int = 10,
                 b: Optional[int] = None):    
    if b is None:
        b = a
    
    lenstr1 = len(string1)
    lenstr2 = len(string2)
    F = [[0] * (lenstr2 + 1) for i in range(lenstr1 + 1)]
    
    for i in range(lenstr1):
        for j in range(lenstr2):
            if string1[i] == string2[j]:
                F[i+1][j+1] = F[i][j] + 1 
            else: 
                F[i+1][j+1] = max(F[i][j+1], F[i+1][j]) 
       
             # transposition_1    
            
            for a in range(1,a+1):
                if j > a-1 and string1[i] == string2[j-a]:  
                    for b in range(1,b+1):
                        if i > b-1 and string2[j] == string1[i-b]:
                            distance = LCS_ch(string1[i-b+1:i], string2[j-a+1:j], a, b)  # call recursive
                            print('str1:', string1[i-b+1:i], 'str2', string2[j-a+1:j])
                            print(a,i,j,string1[i],string2[j-a], string2[j],string1[i-b])
                            F[i+1][j+1] = max (F[i+1][j+1], F[i-b][j-a] + 2 + distance)
                            
                            
            
            
            
    
    
    return(F[lenstr1][lenstr2])


In [24]:
print(LCS_ch('1204', '1402'))

str1:  str2 
1 2 3 0 0 2 2
str1:  str2 
1 3 2 4 4 0 0
str1: 0 str2 0
2 3 3 4 4 2 2
4


In [25]:
def LCS(A,B):
    n = len(A)
    m = len(B)
    F = [[0] * (m + 1) for i in range(n + 1)]
    for i in range(1, n + 1):
        for j in range(1, m + 1):
            if A[i - 1] == B[j - 1]:
                F[i][j] = F[i - 1][j - 1] + 1 
            else: 
                F[i][j] = max(F[i - 1][j], F[i][j - 1]) 
    print(F[n][m])

    Ans = []
    i = n
    j = m
    while i > 0 and j > 0:
        if A[i - 1] == B[j - 1]:
            Ans.append(A[i - 1])
            i -= 1
            j -= 1
        elif F[i - 1][j] == F[i][j]:
            i -= 1 
        else: 
            j -= 1
     
    Ans = Ans[::-1]
    return(Ans)
    

In [26]:
print(LCS('1204', '1402'))

2
['1', '2']


In [34]:
import numpy as np
def LCS_ch_1element(A,B):


    n = len(A)
    m = len(B)
    F = [[0] * (m + 1) for i in range(n + 1)]
    for i in range(1, n + 1):
        for j in range(1, m + 1):
            if A[i - 1] == B[j - 1]:
                F[i][j] = F[i - 1][j - 1] + 1 
                
                
                
            elif i>1 and j>1 and A[i-1]==B[j-2] and A[i-2] == B[j-1]:
                F[i][j] = F[i-2][j-2] + 2 # transposition
                

            else: 
                F[i][j] = max(F[i - 1][j], F[i][j - 1]) 
    print(F[n][m])
    print(np.matrix(F))

    Ans = []
    i = n
    j = m
    while i > 0 and j > 0:
        if A[i - 1] == B[j - 1]:
            #print(Ans)
            Ans.append(A[i - 1])
            i -= 1
            j -= 1
        elif A[i-1]==B[j-2] and A[i-2] == B[j-1]:
            Ans.append(A[i - 1])# transposition
            i -= 1
        elif F[i - 1][j] == F[i][j]:
            i -= 1 
        else: 
            j -= 1
     
    Ans = Ans[::-1]
    return(Ans)

In [35]:
print(LCS_ch_1element('1204', '1402'))

3
[[0 0 0 0 0]
 [0 1 1 1 1]
 [0 1 1 1 2]
 [0 1 1 2 3]
 [0 1 2 3 3]]
['1', '2', '0']
